// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rizckxulygwgxtifzido.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpemNreHVseWd3Z3h0aWZ6aWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1OTAxOTcsImV4cCI6MjA2MjE2NjE5N30.T7H7ZimQypaby0wCnTMI6lfY8AZXfr8pXUwH0OjkxIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);